"""Add bank details to client

Revision ID: af7bd4f5870a
Revises: 9c8b5173fa38
Create Date: 2026-09-19 17:34:35.482166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af7bd4f5870a'
down_revision: Union[str, Sequence[str], None] = '9c8b5173fa38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('bank_name', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('bik', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('account', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('corr_account', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'corr_account')
    op.drop_column('clients', 'account')
    op.drop_column('clients', 'bik')
    op.drop_column('clients', 'bank_name')
    # ### end Alembic commands ###
