"""Add ogrn to company and client

Revision ID: ffa5d074bc47
Revises: af7bd4f5870a
Create Date: 2026-09-19 18:38:11.576440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffa5d074bc47'
down_revision: Union[str, Sequence[str], None] = 'af7bd4f5870a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('ogrn', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('ogrn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'ogrn')
    op.drop_column('clients', 'ogrn')
    # ### end Alembic commands ###
